### ISSUE TITLE
TYPO3 9.5 / fal_gallery 3.0 not working

### ISSUE THREAD

**Issue by wini2** [vertexvaar/fal_gallery#12]
I must confirm that problem #10 still persists. No way to select Default source or/and File storage.

**Comment by vertexvaar** [comment]
When you open the plugin and click the link icon next to the input field a popup opens, you select the parent folder of the folder you want to show in the tree and click on the folder on the right (In this case the highlighte /Gallery/ folder.
This is a TYPO3 core functionality. If this does not work there is a problem with your TYPO3 instance.

![Screenshot from 2019-03-22 13-31-19](https://user-images.githubusercontent.com/5594393/54823017-d26aaf80-4ca6-11e9-8863-a56541d0c35f.png)

**Comment by vertexvaar** [comment]
@wini2 Did this work for you?

**Comment by wini2** [comment]
@vertexvaar

Thank you for your interest. The suggested solution did works only by typing it manually. Because of this restrictions, i did can not use the gallery.
