### ISSUE TITLE
PHP bug in hook

### ISSUE THREAD

**Issue by wolf9k** [vertexvaar/fal_gallery#3]
Anytime any backend user tries to create new file in FAL (not related with FAL Gallery) we get this error:

PHP Catchable Fatal Error: Argument 1 passed to In2code\FalGallery\Hooks\FileMutationSlot::postFileCreate() must be an instance of TYPO3\CMS\Core\Resource\FileInterface, string given in /srv/www/typo-netap/upol16/typo3conf/ext/fal_gallery/Classes/Hooks/FileMutationSlot.php line 86

TYPO3 v.7.6

Thanks for help
Vladimir Kubak

**Comment by vertexvaar** [comment]
I will have a look at that problem this evening. Stay tuned.
