### ISSUE TITLE
TYPO3 CMS version 8.5 and higher: Can not choose folder in PlugIn 

### ISSUE THREAD

**Issue by angeloprevitali** [vertexvaar/fal_gallery#5]
I do use TYPO3 CMS version 8.5.1 with EXT:fal_gallery 2.0.2. If you choose a folder in list view I can not choose a folder. There is nothing to choose.

Can you fix this?

Thanks you very much.

Regards,
Angelo

**Comment by vertexvaar** [comment]
You have to select the parent folder on the left side in the TBE (sometimes twice until it "opens" on the right) and then select the desired folder on the right side.

**Comment by angeloprevitali** [comment]
Thanks. Ah, ok. in the older Version you had to choose the same folder. Not this works. But now i got the following error:

The FAL Gallery Plugin configuration is not correct. Check the List Plugin config. Error: "You might have forgot to configure a folder to display" 

Here is my conf:
http://prntscr.com/e2lk0r
http://prntscr.com/e2lk9m
http://prntscr.com/e2lkfe
http://prntscr.com/e2lklz
http://prntscr.com/e2lkvw

What else do i have to do? On TYPO3 version 6.2 everything works perfect. But on 8.5.1 not..

Any idea?

**Comment by vertexvaar** [comment]
The error means that the resource identifier could not be resolved. Since you're using TYPO3 > 8.3 the LinkService of TYPO3 itself will be used to resolve the t3:// URN and receive the FAL Folder object. Please check that your sys_file_storage with UID 2 is marked as online and the chosen folder is accessible via FAL (if the Filelist module can show the contents of the chosen directory the plugin has to work, too)

**Comment by angeloprevitali** [comment]
Please check that your sys_file_storage with UID 2 is marked as online:
YES. It is. See http://prntscr.com/e2mnee http://prntscr.com/e2mnit http://prntscr.com/e2mnmo
Filelist content: http://prntscr.com/e2mo14
Choosen directory: http://prntscr.com/e2mogz (works, too)

Any idea?

**Comment by vertexvaar** [comment]
Golly! Please update to 2.1.0 (released 7 days ago)

**Comment by angeloprevitali** [comment]
On TER i can only download the version 2.0.2. Can you publish this version on TER? Thx.

**Comment by angeloprevitali** [comment]
2.1.0 works. Problems solved. Great. Thx.

**Comment by vertexvaar** [comment]
Ah, i completely missed the TER upload. Thx for the hint. Uploaded it there, should be available soon.
That's why i prefer and always recommend composer ;)
