### ISSUE TITLE
Not Typo3 9.5 compatible

### ISSUE THREAD

**Issue by the-hotmann** [vertexvaar/fal_gallery#9]
I just installed this version on TYPO3 9.5.3 (as I already updated all TYPO3 installations to 9.5.3) and I cant choose a "Default Source Folder" because I cant select it. 
When I click the button to select the folder I can click on the folders but there is no "accept" button

Could you pls have a look at this?
Thanks in advance!

**Comment by vertexvaar** [comment]
Hi @M4rt1n17 

please try out the current master and check if everything is working.

**Attention**: TYPO3 changed the format of folders and files. FAL Gallery currently supports both but before the next release this will be removed. I will try to provide an upgrade wizard or sth. like that but to be on the safe side update all your plugins by manually selecting the folder and file you want to display.

**Comment by the-hotmann** [comment]
Seems like its working now, thank you :)
